import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DatiServizioService {
   
   opere1 = [
    {nome: "I Girasoli", annoPro:  1888, des: "Questo dipinto iconico raffigura quindici girasoli in piena fioritura disposti in un vaso di terracotta. I fiori sono dipinti con pennellate spesse e impastate, in tonalità di giallo, arancione e marrone. Lo sfondo è di un azzurro intenso, che crea un contrasto cromatico vibrante. I Girasoli sono uno dei soggetti più famosi di Van Gogh e rappresentano la forza vitale e la bellezza della natura.", img: "https://www.artesvelata.it/wp-content/uploads/2022/09/Vincent-Van-Gogh-Vaso-con-quindici-girasoli-3-serie-arte-svelata.jpg",  },
    {nome: "New Brighton Beach ", annoPro: 1986, des: " Quest'opera iconica cattura una scena estiva tipica della costa britannica: la spiaggia di New Brighton affollata di bagnanti. La foto è caratterizzata dall'uso audace del colore e da una composizione dinamica. I soggetti, disposti in modo casuale e apparentemente ignari della macchina fotografica, sono ritratti in atteggiamenti buffi e spesso goffi. L'opera di Parr mette in luce il lato ironico e surreale della vita quotidiana, cogliendo l'assurdità e la banalità del tempo libero di massa. ", img: "https://www.magnumphotos.com/wp-content/uploads/2016/05/cortex/lon6977.jpg ",  },
    {nome: "Gioconda ", annoPro: 1903, des: "Questa celebre opera di Leonardo da Vinci è stata oggetto di una rivisitazione da parte di Picasso nel 1903. La sua Gioconda presenta un volto frammentato e distorto, con colori accesi e forme geometriche che sostituiscono i lineamenti delicati dell'originale. L'opera di Picasso è un omaggio ironico e dissacrante al capolavoro di Leonardo, e rappresenta una riflessione sul ruolo dell'artista e sulla natura dell'arte. ", img: "https://t1.gstatic.com/licensed-image?q=tbn:ANd9GcQsu7yYuRPXNK9eHHSFD2tUYO4stQDb1Ez8vjqGERfs9xqYLLnY_y6lQkPFZa-44cqn",  },
    {nome: "L'Urlo ", annoPro: 1893, des: " Quest'opera iconica è uno dei dipinti più famosi al mondo. Raffigura una figura umana con un'espressione di angoscia e disperazione contro un cielo fiammeggiante. I colori intensi e le linee ondulate creano un senso di movimento e di agitazione. L'opera è considerata un'espressione dell'ansia e dell'alienazione dell'uomo moderno. ", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg/260px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73_cm%2C_National_Gallery_of_Norway.jpg",  },
    {nome: "L'Attesa ", annoPro: 1965, des: "Quest'opera iconica rappresenta Lucio Fontana che taglia una tela con un rasoio. L'immagine è in bianco e nero e coglie un momento di intensa concentrazione e creatività da parte dell'artista. La fotografia è considerata un documento importante dell'Arte Povera e del processo artistico di Fontana. ", img: "https://lavaligiadellartista.files.wordpress.com/2015/10/fontana-taglia-tela-2.jpg ",  },
    {nome: "Jeune fille à la blouse rouge ", annoPro: 1920, des: "Questo ritratto raffigura una giovane donna con una camicetta rossa, seduta su una sedia. La figura è dipinta con pennellate rapide e gestuali, creando un effetto di movimento e spontaneità. I colori vivaci e l'espressione intensa della ragazza trasmettono un senso di vitalità e di energia. Il dipinto è considerato un esempio significativo dello stile espressionista di Soutine, che cattura l'essenza emotiva dei suoi soggetti. ", img: "https://images-cdn.bridgemanimages.com/api/1.0/image/600wm.BRN.6560910.7055475/187477.jpg",  },
    {nome: "La sala da pranzo a Parigi ", annoPro: 1878, des: "Un'opera che rappresenta l'interno di un lussuoso ristorante parigino, con tavoli apparecchiati, camerieri indaffarati e clienti eleganti. La luce artificiale e la prospettiva accentuano la sensazione di vivacità e mondanità. ", img: "https://ilbolive.unipd.it/sites/default/files/2019-02/18-colazione-in-giardino.jpg",  },

   ]
   opere2 = [
    {nome: "La Notte Stellata", annoPro: 1889, des: " Questo dipinto rappresenta la vista notturna dal sanatorio di Saint-Rémy-de-Provence, dove Van Gogh era ricoverato. Il cielo notturno è dominato da un vortice di stelle bianche e gialle, che sembrano muoversi nel cielo. In primo piano si trova un villaggio con case e un campanile, mentre sulla destra si erge un cipresso scuro. La Notte Stellata è una delle opere più famose di Van Gogh ed è considerata un capolavoro dell'arte post-impressionista.", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/300px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",  },
    {nome: "The Cost of Living ", annoPro: 1988, des: " Quest'opera satirica ritrae una coppia di anziani che fanno la spesa in un supermercato. La donna tiene in mano un carrello pieno di prodotti, mentre l'uomo guarda la foto di una famiglia felice su una rivista. L'opera di Parr critica il consumismo e la società materialista, mettendo in luce il divario tra la promessa di una vita felice e la realtà spesso dura e prosaica della vita quotidiana. ", img: "https://scontent.fmxp7-2.fna.fbcdn.net/v/t1.18169-9/15380308_10154790471369509_5064662473436398736_n.jpg?_nc_cat=111&ccb=1-7&_nc_sid=5f2048&_nc_ohc=NvbQB-zFCKcAb4BmpJV&_nc_ht=scontent.fmxp7-2.fna&oh=00_AfB8UDz1L6qzR7dINKgo0jrzzh5YWezII-av6STh7r3S7w&oe=664E1636 ",  },
    {nome: "Guernica  ", annoPro: 1937, des: "Quest'opera monumentale è considerata una delle pitture più importanti del XX secolo. Realizzata in risposta al bombardamento di Guernica da parte dell'aviazione nazista e fascista durante la Guerra Civile Spagnola, Guernica rappresenta la sofferenza e la brutalità della guerra. La tela è dominata da figure contorte e urlanti di esseri umani e animali, dipinti in toni di bianco, nero e grigio. L'opera è priva di qualsiasi riferimento specifico al luogo o al tempo, assumendo così un significato universale di protesta contro la violenza e la sofferenza. ", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Mural_del_Gernika.jpg/800px-Mural_del_Gernika.jpg",  },
    {nome: "Le Giovani Ragazze sul Ponte ", annoPro: 1903, des: " Questo dipinto raffigura tre giovani donne in abiti estivi che si trovano su un ponte. Le figure sono disposte in diagonale e i loro sguardi sono rivolti verso l'osservatore. I colori sono luminosi e gioiosi, ma l'atmosfera è carica di tensione e malinconia. L'opera è stata interpretata come una riflessione sulla fragilità della vita e sulla bellezza effimera della giovinezza. ", img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Munch_Girls_on_the_pier.jpg/260px-Munch_Girls_on_the_pier.jpg",  },
    {nome: "Studio di Robert Rauschenberg ", annoPro: 1964, des: "sQuesta iconica fotografia di Ugo Mulas immortala l'energia creativa e il caos dello studio newyorkese di Robert Rauschenberg nel 1964. Rauschenberg, una figura di spicco del movimento Pop Art, è ritratto al centro dell'immagine, circondato da una moltitudine di dipinti, sculture e altri oggetti. Lo studio appare come uno spazio disordinato e dinamico, riflettendo l'approccio sperimentale ed eclettico di Rauschenberg all'arte. ", img: "https://admin.liarumma.it/wp-content/uploads/2023/01/Senza-nome-23.jpg ",  },
    {nome: "Le Bœuf écorché  ", annoPro: 1927, des: "Quest'opera rappresenta un bue macellato, con la carcassa esposta in modo crudo e realistico. I colori scuri e la pennellatura vigorosa creano un'atmosfera drammatica e cupa. Il dipinto è considerato una delle opere più potenti e disturbanti di Soutine, che esplora temi come la morte, la sofferenza e la brutalità della natura. ", img: "https://media.mutualart.com/Images//2020_09/11/07/074625681/0aeb4ec3-9967-4619-9172-c3d09496a99e.Jpeg",  },
    {nome: "La Signora con l'Ulster ", annoPro: 1882, des: "Un'opera emblematica della maturità artistica di De Nittis, ritrae una donna elegante avvolta in un mantello nero con un parasole e un cagnolino. La scena urbana è resa con pennellate rapide e luminose, con contrasti di colore tra il nero del mantello e il bianco della camicetta. ", img: "https://www.artuu.it/wp-content/uploads/2024/03/SOCIAL-DENITTIS-1080x1080-Signora-con-il-cane-1024x1024.jpg",  },
   ]
   
  constructor() { }

  getOpera1(){
    return this.opere1
  }
  getOpera2(){
    return this.opere2
  }
}
